<?php

namespace Pkr\BuzzBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QueryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QueryRepository extends EntityRepository
{
}